apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-to-mp3-ms-notification-service
  labels:
    app: video-to-mp3-ms-notification-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: video-to-mp3-ms-notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: video-to-mp3-ms-notification-service
    spec:
      containers:
        - name: video-to-mp3-ms-notification-service
          image: romanojha/video-to-mp3-ms-notification-service
          envFrom:
            - configMapRef:
                name: video-to-mp3-ms-notification-service-configmap
            - secretRef:
                name: video-to-mp3-ms-notification-service-secret
